from django.db import models

class Proveedor(models.Model):
  cod_cpa01 = models.CharField(db_column='COD_CPA01', max_length=10, unique=True)
  id_tipo_documento_gv = models.IntegerField(db_column='ID_TIPO_DOCUMENTO_GV', blank=True, null=True)
  n_cuit = models.CharField(db_column='N_CUIT', max_length=15, blank=True, null=True)
  nom_provee = models.CharField(db_column='NOM_PROVEE', max_length=60)
  domicilio = models.CharField(db_column='DOMICILIO', max_length=30, blank=True, null=True)
  localidad = models.CharField(db_column='LOCALIDAD', max_length=20, blank=True, null=True)
  c_postal = models.CharField(db_column='C_POSTAL', max_length=8, blank=True, null=True)
  id_cpa57 = models.IntegerField(db_column='ID_CPA57', blank=True, null=True)
  telefono_1 = models.CharField(db_column='TELEFONO_1', max_length=30, blank=True, null=True)
  telefono_2 = models.CharField(db_column='TELEFONO_2', max_length=30, blank=True, null=True)
  telefono_movil = models.CharField(db_column='TELEFONO_MOVIL', max_length=30, blank=True, null=True)
  e_mail = models.CharField(db_column='E_MAIL', max_length=255, blank=True, null=True)
  web = models.CharField(db_column='WEB', max_length=60, blank=True, null=True)
  nom_fant = models.CharField(db_column='NOM_FANT', max_length=60, blank=True, null=True)
  domicilio_comercial = models.CharField(db_column='DOMICILIO_COMERCIAL', max_length=30, blank=True, null=True)
  id_gva151 = models.IntegerField(db_column='ID_GVA151', blank=True, null=True)
  n_iva = models.CharField(db_column='N_IVA', max_length=160, blank=True, null=True)
  fecha_alta = models.DateTimeField(db_column='FECHA_ALTA', blank=True, null=True)
  fecha_inha = models.DateTimeField(db_column='FECHA_INHA', blank=True, null=True)
  observacio = models.CharField(db_column='OBSERVACIO', max_length=60, blank=True, null=True)
  observac_2 = models.CharField(db_column='OBSERVAC_2', max_length=60, blank=True, null=True)
  id_categoria_iva_cond_iva = models.IntegerField(db_column='ID_CATEGORIA_IVA_COND_IVA', blank=True, null=True)
  tipo = models.CharField(db_column='TIPO', max_length=1, blank=True, null=True)
  n_ing_brut = models.CharField(db_column='N_ING_BRUT', max_length=20, blank=True, null=True)
  cm_vigencia_coeficiente = models.DateTimeField(db_column='CM_VIGENCIA_COEFICIENTE', blank=True, null=True)
  iva_l = models.BooleanField(db_column='IVA_L', blank=True, null=True)
  iva_s = models.BooleanField(db_column='IVA_S', blank=True, null=True)
  ii_l = models.BooleanField(db_column='II_L', blank=True, null=True)
  ii_s = models.BooleanField(db_column='II_S', blank=True, null=True)
  calcu_ret = models.CharField(db_column='CALCU_RET', max_length=1, blank=True, null=True)
  texto_ib_1 = models.CharField(db_column='TEXTO_IB_1', max_length=60, blank=True, null=True)
  texto_ib_2 = models.CharField(db_column='TEXTO_IB_2', max_length=60, blank=True, null=True)
  texto_ib_3 = models.CharField(db_column='TEXTO_IB_3', max_length=60, blank=True, null=True)
  texto_ib_4 = models.CharField(db_column='TEXTO_IB_4', max_length=60, blank=True, null=True)
  id_operacion_afip_rg_3685_tipo_operacion_compras = models.IntegerField(db_column='ID_OPERACION_AFIP_RG_3685_TIPO_OPERACION_COMPRAS', blank=True, null=True)
  id_tipo_comprobante_afip_rg_3685_comprobante_compras = models.IntegerField(db_column='ID_TIPO_COMPROBANTE_AFIP_RG_3685_COMPROBANTE_COMPRAS', blank=True, null=True)
  rg_3685_genera_informacion = models.BooleanField(db_column='RG_3685_GENERA_INFORMACION', blank=True, null=True)
  rg_3572_empresa_vinculada_proveedor = models.BooleanField(db_column='RG_3572_EMPRESA_VINCULADA_PROVEEDOR', blank=True, null=True)
  id_rg_3572_tipo_operacion_habitual_proveedor = models.IntegerField(db_column='ID_RG_3572_TIPO_OPERACION_HABITUAL_PROVEEDOR', blank=True, null=True)
  contfiscal = models.BooleanField(db_column='CONTFISCAL', blank=True, null=True)
  t_form = models.CharField(db_column='T_FORM', max_length=1, blank=True, null=True)
  cai = models.CharField(db_column='CAI', max_length=14, blank=True, null=True)
  fecha_vto = models.DateTimeField(db_column='FECHA_VTO', blank=True, null=True)
  citi_opera = models.CharField(db_column='CITI_OPERA', max_length=1, blank=True, null=True)
  citi_tipo = models.CharField(db_column='CITI_TIPO', max_length=1, blank=True, null=True)
  id_iva_clasificacion_siap_clas_siap = models.IntegerField(db_column='ID_IVA_CLASIFICACION_SIAP_CLAS_SIAP', blank=True, null=True)
  lim_credit = models.DecimalField(db_column='LIM_CREDIT', max_digits=22, decimal_places=7, blank=True, null=True)
  moneda_limite_credito_cte = models.BooleanField(db_column='MONEDA_LIMITE_CREDITO_CTE', blank=True, null=True)
  clausula = models.BooleanField(db_column='CLAUSULA', blank=True, null=True)
  inf_iva = models.CharField(db_column='INF_IVA', max_length=1, blank=True, null=True)
  num_automa = models.CharField(db_column='NUM_AUTOMA', max_length=1, blank=True, null=True)
  letra_habi = models.CharField(db_column='LETRA_HABI', max_length=1, blank=True, null=True)
  id_condicion_compra = models.IntegerField(db_column='ID_CONDICION_COMPRA', blank=True, null=True)
  porc_desc = models.DecimalField(db_column='PORC_DESC', max_digits=22, decimal_places=7, blank=True, null=True)
  mon_cte_ha = models.CharField(db_column='MON_CTE_HA', max_length=1, blank=True, null=True)
  inc_iva_li = models.BooleanField(db_column='INC_IVA_LI', blank=True, null=True)
  inc_ii_lis = models.BooleanField(db_column='INC_II_LIS', blank=True, null=True)
  edita_comprobante_referencia_remito = models.CharField(db_column='EDITA_COMPROBANTE_REFERENCIA_REMITO', max_length=1, blank=True, null=True)
  defecto_comprobante_referencia_remito = models.CharField(db_column='DEFECTO_COMPROBANTE_REFERENCIA_REMITO', max_length=3, blank=True, null=True)
  edita_comprobante_referencia_factura_remito = models.CharField(db_column='EDITA_COMPROBANTE_REFERENCIA_FACTURA_REMITO', max_length=1, blank=True, null=True)
  defecto_comprobante_referencia_factura_remito = models.CharField(db_column='DEFECTO_COMPROBANTE_REFERENCIA_FACTURA_REMITO', max_length=3, blank=True, null=True)
  ingresa_factura_sin_remito_asociado = models.BooleanField(db_column='INGRESA_FACTURA_SIN_REMITO_ASOCIADO', blank=True, null=True)
  edita_comprobante_referencia_factura = models.CharField(db_column='EDITA_COMPROBANTE_REFERENCIA_FACTURA', max_length=1, blank=True, null=True)
  defecto_comprobante_referencia_factura = models.CharField(db_column='DEFECTO_COMPROBANTE_REFERENCIA_FACTURA', max_length=3, blank=True, null=True)
  exporta = models.BooleanField(db_column='EXPORTA', blank=True, null=True)
  id_sucursal_destino = models.IntegerField(db_column='ID_SUCURSAL_DESTINO', blank=True, null=True)
  id_sba01_cfondo_pm = models.IntegerField(db_column='ID_SBA01_CFONDO_PM', blank=True, null=True)
  id_sba01_cfunica_pm = models.IntegerField(db_column='ID_SBA01_CFUNICA_PM', blank=True, null=True)
  pago_che = models.BooleanField(db_column='PAGO_CHE', blank=True, null=True)
  dias_ch_pm = models.IntegerField(db_column='DIAS_CH_PM', blank=True, null=True)
  cbu = models.CharField(db_column='CBU', max_length=22, blank=True, null=True)
  descripcion_cbu = models.CharField(db_column='DESCRIPCION_CBU', max_length=30, blank=True, null=True)
  cbu_2 = models.CharField(db_column='CBU_2', max_length=22, blank=True, null=True)
  descripcion_cbu_2 = models.CharField(db_column='DESCRIPCION_CBU_2', max_length=30, blank=True, null=True)
  cbu_3 = models.CharField(db_column='CBU_3', max_length=22, blank=True, null=True)
  descripcion_cbu_3 = models.CharField(db_column='DESCRIPCION_CBU_3', max_length=30, blank=True, null=True)
  orden = models.CharField(db_column='ORDEN', max_length=60, blank=True, null=True)
  habil_pm = models.BooleanField(db_column='HABIL_PM', blank=True, null=True)
  observaciones = models.TextField(db_column='OBSERVACIONES', blank=True, null=True)
  texto = models.TextField(db_column='TEXTO', blank=True, null=True)
  tipo_doc = models.IntegerField(db_column='TIPO_DOC', blank=True, null=True)
  saldo_cc_unidades = models.DecimalField(db_column='SALDO_CC_UNIDADES', max_digits=22, decimal_places=7, blank=True, null=True)
  cod_descrip = models.TextField(db_column='COD_DESCRIP', blank=True, null=True)
  proveedor_cm_jurisdiccion = models.JSONField(db_column='PROVEEDOR_CM_JURISDICCION', blank=True, null=True)
  retenciones = models.JSONField(db_column='RETENCIONES', blank=True, null=True)
  articulos = models.JSONField(db_column='ARTICULOS', blank=True, null=True)
  conceptos = models.JSONField(db_column='CONCEPTOS', blank=True, null=True)
  contactos = models.JSONField(db_column='CONTACTOS', blank=True, null=True)
  sucursales = models.JSONField(db_column='SUCURSALES', blank=True, null=True)
