# Generated by Django 3.2.25 on 2025-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cod_cpa01',
            field=models.CharField(blank=True, db_column='COD_CPA01', max_length=10, null=True, unique=True),
        ),
    ]
