# Generated by Django 3.2.25 on 2025-05-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proveedores', '0002_alter_proveedor_cod_cpa01'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='username_django',
            field=models.ForeignKey(blank=True, db_column='USERNAME_DJANGO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to=settings.AUTH_USER_MODEL),
        ),
    ]
