# Generated by Django 3.2.25 on 2025-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0003_proveedor_username_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nom_prov',
            field=models.CharField(blank=True, db_column='NOM_PROV', max_length=100, null=True),
        ),
    ]
