# Generated by Django 3.2.25 on 2025-05-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0004_proveedor_nom_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cod_pais',
            field=models.CharField(blank=True, db_column='COD_PAIS', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nom_pais',
            field=models.CharField(blank=True, db_column='NOM_PAIS', max_length=60, null=True),
        ),
    ]
