# Generated by Django 3.2.25 on 2025-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0005_auto_20250526_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cond_iva',
            field=models.CharField(blank=True, db_column='COND_IVA', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='desc_categoria_iva',
            field=models.CharField(blank=True, db_column='DESC_CATEGORIA_IVA', max_length=50, null=True),
        ),
    ]
