# Generated by Django 3.2.25 on 2025-06-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0006_auto_20250527_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Factura A', 'Factura A'), ('Factura B', 'Factura B'), ('Factura C', 'Factura C'), ('Nota de Crédito', 'Nota de Crédito'), ('Nota de Débito', 'Nota de Débito')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('archivo', models.FileField(upload_to='comprobantes/%Y/%m/%d/')),
                ('estado', models.CharField(default='Recibido', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='Proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
