# Generated by Django 3.2.25 on 2025-06-02 17:12

import Proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0007_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cm05_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cm05_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='excl_ganancias_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='excl_ganancias_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='excl_iibb_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='excl_iibb_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ing_brutos_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ing_brutos_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='no_ret_ganancias_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='no_ret_ganancias_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='no_ret_iibb_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='no_ret_iibb_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.FileField(upload_to=Proveedores.models.comprobante_upload_path),
        ),
    ]
