# Generated by Django 3.2.25 on 2025-06-04 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proveedores', '0008_auto_20250602_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpaContactosProveedorHabitual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cpa_contactos_proveedor_habitual_sql', models.IntegerField(blank=True, db_column='ID_CPA_CONTACTOS_PROVEEDOR_HABITUAL_SQL', help_text='ID de la tabla original en SQL Server, se llena después de la sincronización.', null=True)),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=20, null=True)),
                ('defecto', models.CharField(blank=True, db_column='DEFECTO', max_length=1, null=True)),
                ('cod_provee', models.CharField(blank=True, db_column='COD_PROVEE', max_length=6, null=True)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=30, null=True)),
                ('telefono_movil', models.CharField(blank=True, db_column='TELEFONO_MOVIL', max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=30, null=True)),
                ('observacion', models.CharField(blank=True, db_column='OBSERVACION', max_length=60, null=True)),
                ('tipo_documento', models.SmallIntegerField(blank=True, db_column='TIPO_DOCUMENTO', null=True)),
                ('numero_documento', models.CharField(blank=True, db_column='NUMERO_DOCUMENTO', max_length=20, null=True)),
                ('envia_pdf_oc', models.CharField(blank=True, db_column='ENVIA_PDF_OC', max_length=1, null=True)),
                ('envia_pdf_op', models.CharField(blank=True, db_column='ENVIA_PDF_OP', max_length=1, null=True)),
                ('username_django', models.ForeignKey(blank=True, db_column='USERNAME_DJANGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proveedores_cpacontactosproveedorhabitual_staging',
                'managed': True,
                'unique_together': {('cod_provee', 'nombre')},
            },
        ),
    ]
