# Generated by Django 3.2.25 on 2026-09-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0007_proveedor_excl_iva_file'),
        ('Proveedores', '0008_turno_reserva_fields'),
    ]

    operations = [
    ]
