# Generated by Django 3.2.25 on 2025-06-05 13:49

import Proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0009_cpacontactosproveedorhabitual'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cbu_file',
            field=models.FileField(blank=True, null=True, upload_to=Proveedores.models.documentos_upload_path),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cbu_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
