# Generated by Django 3.2.25 on 2025-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0010_auto_20250605_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='Num_Oc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Compra asociada'),
        ),
    ]
